version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/CI-CD-Pipeline
    overwrite: true  # Assuming 'overwrite' is the correct property for file_exists_behavior

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root

